import type { ClothingItem } from '@/types'

// 占位数据——用不同颜色区分品类，后续替换为 Midjourney 生成的实物图
// 每件的 image 字段为纯色 SVG data URI，方便拖拽原型验证
export const MOCK_CLOTHING: ClothingItem[] = [
  // ===== 上衣 =====
  { id: 'top-01', owner_id: null, name: '白色毛衣', category: 'top', sub_category: 'sweater', color: '#F5F5F5', color_group: 'light', material: '针织', pattern: null, fit: '合身', length: '常规', neckline: '圆领', style_tags: ['简约'], image_url: '/top-white-sweater-01.png?v=1', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-02', owner_id: null, name: '条纹衬衫', category: 'top', sub_category: 'shirt', color: '#A8C4D4', color_group: 'cool', material: '棉', pattern: '蓝白竖条纹', fit: '合身', length: '常规', neckline: '翻领', detail: '小翻领，前襟纽扣，长袖带袖口，宽松版型', style_tags: ['法式', '简约'], image_url: '/top-blue-shirt-02.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-04', owner_id: null, name: '白色泡泡袖', category: 'top', sub_category: 'puff_sleeve', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: null, fit: '修身', length: '短款', neckline: '方领', detail: '方领设计，蓬松泡泡袖袖口收拢，短款露腰设计', style_tags: ['甜美', '复古'], image_url: '/top-white-puffy-sleeves-04.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-05', owner_id: null, name: '长袖印花斜肩上衣', category: 'top', sub_category: 'off_shoulder_ls', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: '粉色花朵绿叶晕染', fit: '修身', length: '常规', neckline: '一字肩', detail: '不对称斜肩设计，一侧露肩一侧有袖，腹部褶皱设计，油画质感印花', style_tags: ['辣妹风'], image_url: '/top-printed off-the-shoulder-08.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-06', owner_id: null, name: '灰色卫衣', category: 'top', sub_category: 'sweatshirt', color: '#9A9A9A', color_group: 'neutral', material: '棉', pattern: null, fit: '宽松', length: '常规', neckline: '圆领', detail: '圆领宽松版型，落肩设计，罗纹下摆和袖口', style_tags: ['街头', '运动'], image_url: '/top-gray-sweatshirt-05.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-07', owner_id: null, name: '工装衬衫', category: 'top', sub_category: 'shirt', color: '#B4C1A8', color_group: 'cool', material: '棉', pattern: null, fit: '合身', length: '常规', neckline: '翻领', detail: '翻领设计，胸前两个带盖口袋，长袖', style_tags: ['工装', '街头'], image_url: '/top-workwear-shirt-07.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-08', owner_id: null, name: '米色亨利衫', category: 'top', sub_category: 'henley', color: '#D4C5A0', color_group: 'warm', material: '棉', pattern: null, fit: '修身', length: '常规', neckline: '翻领', detail: '无领半开襟两粒扣设计，修身版型，长袖', style_tags: ['简约', '美式复古'], image_url: '/top-beige-herry-shirt-06.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-03', owner_id: null, name: '燕麦色针织', category: 'top', sub_category: 'cardigan', color: '#D4C5A0', color_group: 'warm', material: '针织', pattern: null, fit: '宽松', length: '中长', neckline: '无领', detail: 'V领，长袖，门襟敞开呈自然垂落状', style_tags: ['甜美', '复古'], image_url: '/top-oat-knitting-03.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-09', owner_id: null, name: '酒红色露肩鱼骨上衣', category: 'top', sub_category: 'off_shoulder_corset', color: '#8B2252', color_group: 'warm', material: '棉+氨纶', pattern: null, fit: '修身', length: '短款', neckline: '一字肩', detail: '一字领露肩设计，胸前纵向鱼骨线分割交叉绑带，修身短款版型，长袖', style_tags: ['辣妹风', '法式'], image_url: '/top-off-shoulder-corset-09.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-10', owner_id: null, name: '蓝色V领波点挂脖上衣', category: 'top', sub_category: 'halter', color: '#6B8FA3', color_group: 'cool', material: '雪纺', pattern: '白色波点均匀分布', fit: '修身', length: '短款', neckline: '吊带', detail: 'V领挂脖系带设计，较宽松版型，白色波点均匀分布，下摆荷叶边设计，轻盈飘逸', style_tags: ['法式', '复古'], image_url: '/top-polkadot-halter-10.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-11', owner_id: null, name: '无袖挂脖上衣', category: 'top', sub_category: 'halter', color: '#E8B4B8', color_group: 'warm', material: '欧根纱', pattern: null, fit: '修身', length: '短款', neckline: '吊带', detail: '挂脖系带设计，领口细微褶皱，轻盈飘逸下摆', style_tags: ['辣妹风', '甜美'], image_url: '/top-pink-halter-11.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-12', owner_id: null, name: '长袖一字肩上衣', category: 'top', sub_category: 'off_shoulder_ls', color: '#2A2A2A', color_group: 'dark', material: '棉+氨纶', pattern: null, fit: '修身', length: '常规', neckline: '一字肩', detail: '收腰剪裁', style_tags: ['简约', '辣妹风'], image_url: '/top-off-shoulder-longsleeve-12.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-13', owner_id: null, name: '短袖方领泡泡袖上衣', category: 'top', sub_category: 'puff_sleeve', color: '#DDA040', color_group: 'warm', material: '棉', pattern: null, fit: '修身', length: '短款', neckline: '方领', detail: '方领设计，双肩细褶，袖口微收，腰部宽松自然不收腰', style_tags: ['甜美', '复古'], image_url: '/top-puff-sleeve-13.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'top-14', owner_id: null, name: '短袖一字肩修身T恤', category: 'top', sub_category: 'off_shoulder_tee', color: '#A8C4D4', color_group: 'cool', material: '棉', pattern: null, fit: '修身', length: '短款', neckline: '一字肩', style_tags: ['简约', '辣妹风'], image_url: '/top-off-shoulder-tee-14.png', layer_order: 2, occupies_full_body: false, source: 'system' },

  // ===== 下装 =====
  { id: 'bottom-01', owner_id: null, name: '直筒牛仔裤', category: 'bottom', sub_category: 'jeans', color: '#6B8FA3', color_group: 'cool', material: '牛仔', pattern: null, fit: '合身', length: '常规', style_tags: ['简约', '复古'], image_url: '/bottom-blue-jieans-01.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-05', owner_id: null, name: '高腰卷边短裤', category: 'bottom', sub_category: 'shorts', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: null, fit: '宽松', length: '短款', detail: '高腰版型，裤耳设计，裤脚宽边卷边', style_tags: ['简约', '法式'], image_url: '/bottom-shorts-white-highwaist-cuffed-02.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-11', owner_id: null, name: '裸色蛋糕纱裙', category: 'bottom', sub_category: 'tiered_tulle_skirt', color: '#E8C8B0', color_group: 'warm', material: '薄纱', pattern: null, fit: '合身', length: '短款', detail: '5层蛋糕裙设计，每层均匀荷叶边分布，侧边隐形拉链', style_tags: ['甜美', '法式'], image_url: '/bottom-nude-tiered-tulle-mini-skirt-03.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-12', owner_id: null, name: '白色A字半裙', category: 'bottom', sub_category: 'a_line_skirt', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: '素色', fit: '合身', length: '中长', detail: 'A字版型，裙摆自然散开至小腿，哑光棉质面料，侧边隐形拉链，下摆明线缝边', style_tags: ['简约', '法式'], image_url: '/bottom-white-a-line-maxi-skirt-04.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-13', owner_id: null, name: '油画花卉A字半裙', category: 'bottom', sub_category: 'a_line_skirt', color: '#C4886A', color_group: 'warm', material: '混纺', pattern: '油画笔触花卉图案', fit: '合身', length: '中长', detail: '自然A字廓形，高腰设计，裙摆自然散开至小腿，油画笔触风格花卉图案，色彩浓郁有肌理感，侧边隐形拉链', style_tags: ['法式', '复古'], image_url: '/bottom-floral-oil-painting-a-line-midi-skirt-05.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-14', owner_id: null, name: '米白拼接蕾丝半裙', category: 'bottom', sub_category: 'a_line_skirt', color: '#F5F0E8', color_group: 'light', material: '缎面', pattern: '下摆蕾丝拼接', fit: '合身', length: '中长', detail: 'A字版型，裙身主体缎面面料，下摆拼接宽幅蕾丝边，蕾丝花纹细腻清晰，侧边隐形拉链', style_tags: ['法式', '优雅'], image_url: '/bottom-cream-satin-lace-hem-a-line-skirt-06.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-15', owner_id: null, name: '米白鱼尾裙', category: 'bottom', sub_category: 'mermaid_skirt', color: '#F5F0E8', color_group: 'light', material: '醋酸', pattern: '素色', fit: '修身', length: '中长', detail: '臀部大腿处修身包裹，膝盖以下裙摆向外散开呈鱼尾状，弹力醋酸面料，后中开衩', style_tags: ['优雅', '法式'], image_url: '/bottom-solid-mermaid-midi-skirt-07.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-16', owner_id: null, name: '灰色短款百褶裙', category: 'bottom', sub_category: 'pleated_skirt', color: '#8A8A8A', color_group: 'neutral', material: '聚酯', pattern: '均匀细褶', fit: '合身', length: '短款', detail: '从腰头均匀细密褶皱自然散开，裙长至大腿中部，宽腰封设计，侧边隐形拉链', style_tags: ['学院', '日系'], image_url: '/bottom-gray-mini-pleated-skirt-08.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-17', owner_id: null, name: '深色包臀短裙', category: 'bottom', sub_category: 'pencil_skirt', color: '#2A2A2A', color_group: 'dark', material: '针织', pattern: '素色', fit: '紧身', length: '短款', detail: '高腰设计，裙身紧贴身体曲线向下收窄至大腿中部，弹力针织面料，后中开衩', style_tags: ['简约', '辣妹风'], image_url: '/bottom-dark-knit-pencil-mini-skirt-09.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-18', owner_id: null, name: '靛蓝高腰阔腿牛仔裤', category: 'bottom', sub_category: 'wide_jeans', color: '#4A6B8A', color_group: 'cool', material: '牛仔', pattern: '水洗猫须', fit: '宽松', length: '长款', detail: '裤腿从大腿处向下逐渐放宽，裤长至脚面，靛蓝色水洗丹宁，轻微猫须纹理和自然磨白，腰带环设计，前门襟拉链', style_tags: ['复古', '街头'], image_url: '/bottom-indigo-wide-leg-jeans-10.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-19', owner_id: null, name: '宽松工装长裤', category: 'bottom', sub_category: 'cargo', color: '#8A7A5A', color_group: 'neutral', material: '棉', pattern: '素色', fit: '宽松', length: '长款', detail: '直筒宽松版型，大腿两侧大口袋带翻盖，厚实斜纹棉布质感，腰带环设计，膝盖处细微立体褶', style_tags: ['工装', '街头'], image_url: '/bottom-cargo-straight-pants-11.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-20', owner_id: null, name: '条纹阔腿长裤', category: 'bottom', sub_category: 'trousers', color: '#D4C5A0', color_group: 'warm', material: '混纺', pattern: '竖条纹', fit: '宽松', length: '长款', detail: '裤腿从大腿处向下逐渐放宽，裤长至脚面，竖条纹纹理面料，轻微悬垂感，侧边隐藏式拉链，裤腿中央细微熨烫折痕', style_tags: ['简约', '通勤'], image_url: '/bottom-stripe-wide-leg-trousers-12.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'bottom-21', owner_id: null, name: '素色A字半裙', category: 'bottom', sub_category: 'a_line_skirt', color: '#D4C8B8', color_group: 'warm', material: '棉', pattern: '素色', fit: '合身', length: '中长', detail: '自然A字廓形，高腰设计，裙摆自然散开，裙长及膝，哑光棉质面料，侧边隐形拉链，下摆明线缝边', style_tags: ['简约', '法式'], image_url: '/bottom-solid-a-line-midi-skirt-13.png', layer_order: 3, occupies_full_body: false, source: 'system' },

  // ===== 连衣裙 =====
  { id: 'dress-01', owner_id: null, name: '无袖小黑裙', category: 'dress', sub_category: 'mini', color: '#2A2A2A', color_group: 'dark', material: '聚酯', pattern: null, fit: '修身', length: '短款', neckline: '圆领', detail: '小圆领，修身收腰裁剪，较有廓形感，裙摆自然微扩至膝上，后背隐形拉链', style_tags: ['极简', '法式'], image_url: '/dress-black-classic-03.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-02', owner_id: null, name: '短袖碎花茶歇裙', category: 'dress', sub_category: 'midi', color: '#F5F0D0', color_group: 'light', material: '棉', pattern: '红色碎花均匀分布', fit: '修身', length: '中长', neckline: 'V领', detail: 'V领交叉门襟系带收腰，裙摆自然散开', style_tags: ['法式', '复古'], image_url: '/dress-tea-floral-04.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-05', owner_id: null, name: '一字肩白色连衣裙', category: 'dress', sub_category: 'off_shoulder_dress', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: null, fit: '修身', length: '中长', neckline: '一字肩', detail: '腰间交叉绑带收腰加蝴蝶结设计，袖口小飞袖设计，A字裙摆自然散开，裙子下摆三分之一处有拼接线，裙摆细密蕾丝内衬', style_tags: ['法式', '优雅'], image_url: '/dress-white-offshoulder-waist-tie-00.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-06', owner_id: null, name: '蓝色波点连衣裙', category: 'dress', sub_category: 'midi', color: '#1A2A4A', color_group: 'dark', material: '聚酯', pattern: '白色波点', fit: '修身', length: '中长', neckline: '翻领', detail: '衬衫翻领设计，短袖，上半身纽扣门襟，腰间细褶设计', style_tags: ['法式', '复古'], image_url: '/dress-navy-polka-dot-02.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-07', owner_id: null, name: '雾粉雪纺连衣裙', category: 'dress', sub_category: 'midi', color: '#E8C4C9', color_group: 'warm', material: '雪纺', pattern: null, fit: '修身', length: '中长', neckline: '蝴蝶结飘带', detail: '领口蝴蝶结飘带设计，长袖喇叭袖，袖口微收，收腰A字版型，裙摆自然散开至小腿，轻薄雪纺面料有轻微透感', style_tags: ['甜美', '法式'], image_url: '/dress-misty-pink-chiffon-bow-a-line-05.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-08', owner_id: null, name: '吊带花卉连衣裙', category: 'dress', sub_category: 'midi', color: '#2A2A2A', color_group: 'dark', material: '聚酯', pattern: '小玫瑰花均匀排列', fit: '修身', length: '中长', neckline: 'V领', detail: '细吊带，V领，收腰设计，裙摆自然散开至小腿，亮面面料', style_tags: ['甜美', '法式'], image_url: '/dress-black-spaghetti-strap-floral-06.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-09', owner_id: null, name: '藕粉V领无袖连衣裙', category: 'dress', sub_category: 'midi', color: '#D4C5C2', color_group: 'warm', material: '聚酯', pattern: null, fit: '修身', length: '中长', neckline: 'V领', detail: 'V领深度适中，无袖，腰间交叉绑带收腰，裙摆自然散开至小腿，素色哑光面料，侧边隐形拉链', style_tags: ['简约', '法式'], image_url: '/dress-dusty-rose-vneck-sleeveless-tie-waist-07.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-10', owner_id: null, name: '檬黄挂脖露背连衣裙', category: 'dress', sub_category: 'maxi', color: '#F5E68C', color_group: 'warm', material: '丝绸', pattern: null, fit: '修身', length: '长款', neckline: '挂脖', detail: '挂脖系带设计，正面圆领无袖，背部大面积露背，收腰剪裁，裙摆自然垂坠至脚踝，轻盈缎面光泽感', style_tags: ['优雅', '法式'], image_url: '/dress-lemon-yellow-halter-backless-maxi-08.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-11', owner_id: null, name: '白色吊带一字领长裙', category: 'dress', sub_category: 'off_shoulder_dress', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: null, fit: '修身', length: '长款', neckline: '一字领', detail: '露肩设计，细吊带横跨肩部，收腰A字版型，裙摆自然散开至脚踝，素色哑光棉质面料', style_tags: ['简约', '优雅'], image_url: '/dress-white-offshoulder-spaghetti-strap-maxi-09.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-12', owner_id: null, name: '清新绿波点挂脖连衣裙', category: 'dress', sub_category: 'mini', color: '#C1D8C3', color_group: 'cool', material: '雪纺', pattern: '白色小波点均匀分布', fit: '修身', length: '短款', neckline: '挂脖', detail: '挂脖设计，V领开口，领口两侧飘带自然垂落，收腰A字版型，裙摆散开至膝上，轻盈雪纺面料，裙摆细微褶皱纹理', style_tags: ['甜美', '法式'], image_url: '/dress-fresh-green-polka-dot-halter-mini-10.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-13', owner_id: null, name: '珍珠白日系连衣裙', category: 'dress', sub_category: 'midi', color: '#E8E4DF', color_group: 'light', material: '聚酯', pattern: null, fit: '修身', length: '中长', neckline: '小圆领', detail: '娃娃领，领口蝴蝶结系带装饰，短袖，袖口明线收口，收腰大摆A字版型，裙身自然竖向虚压褶，裙摆蓬松散开至小腿，后背拉链，哑光面料，整体廓形端庄优雅', style_tags: ['优雅', '日系'], image_url: '/dress-pearl-white-midi-bow-a-line-11.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'dress-14', owner_id: null, name: '淡蓝印花旗袍', category: 'dress', sub_category: 'qipao', color: '#A8C4D4', color_group: 'cool', material: '丝绸', pattern: '淡蓝底素雅暗纹印花', fit: '修身', length: '中长', neckline: '立领', detail: '小立领，斜襟盘扣，短袖，修身版型，腰部收省道，裙长至小腿，侧边开衩，淡蓝底暗纹印花，缎面光泽感', style_tags: ['优雅', '中式'], image_url: '/dress-light-blue-qipao-satin-midi-12.png', layer_order: 1, occupies_full_body: true, source: 'system' },
  { id: 'openai_1782704425_0f60c15c', owner_id: null, name: '黑色风衣裙', category: 'dress', sub_category: 'mini', color: '#2A2A2A', color_group: 'dark', material: '棉', pattern: null, fit: '合身', length: '短款', neckline: '翻领', detail: '翻领，双排扣前襟，腰部配同色系可拆卸腰带，肩部有肩章装饰，裙摆自然散开至膝盖以上，挺括棉质面料', style_tags: ['通勤', '帅气'], image_url: '/openai_1782704425_0f60c15c.png', layer_order: 1, occupies_full_body: true, source: 'system' },

  // ===== 外套 =====
  { id: 'openai_1780210048_e1c8b801', owner_id: null, name: '黑色修身西装外套', category: 'outerwear', sub_category: 'blazer', color: '#2A2A2A', color_group: 'dark', material: '羊毛混纺', pattern: null, fit: '修身', length: '常规', neckline: '翻领', detail: '平驳领，单排两粒扣，长袖袖口有三粒装饰扣，两侧翻盖口袋，后中开衩，挺括羊毛混纺面料质感', style_tags: ['简约', '通勤'], image_url: '/openai_1780210048_e1c8b801.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780210069_a9e7093e', owner_id: null, name: '蓝色牛仔夹克', category: 'outerwear', sub_category: 'jacket', color: '#7B9CB5', color_group: 'cool', material: '牛仔', pattern: '水洗磨白', fit: '合身', length: '短款', neckline: '翻领', detail: '翻领，前襟纽扣门襟，长袖袖口有纽扣开合，胸前两个翻盖口袋，下摆有调节袢扣，水洗丹宁面料轻微磨白', style_tags: ['街头', '复古'], image_url: '/openai_1780210069_a9e7093e.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780210086_3afd29e7', owner_id: null, name: '卡其色经典风衣', category: 'outerwear', sub_category: 'trench', color: '#D4C5A0', color_group: 'warm', material: '棉', pattern: null, fit: '合身', length: '中长', neckline: '翻领', detail: '翻领，双排扣前襟，长袖，肩部有肩章装饰，腰部配有同色系可拆卸腰带，下摆至大腿中部，防泼水棉质面料', style_tags: ['法式', '通勤'], image_url: '/openai_1780210086_3afd29e7.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780210098_243dd31e', owner_id: null, name: '黑白拼色棒球服', category: 'outerwear', sub_category: 'bomber', color: '#2A2A2A', color_group: 'dark', material: '尼龙', pattern: '黑白撞色拼接', fit: '宽松', length: '短款', neckline: '圆领', detail: '圆领，前襟按扣门襟，落肩长袖，袖身与衣身撞色拼接，罗纹领口袖口和下摆，胸口有刺绣字母徽章', style_tags: ['街头', '运动'], image_url: '/openai_1780210098_243dd31e.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  // 男生单品
  { id: 'openai_1780357464_553a010c', owner_id: null, gender: 'male', name: '黑色飞行员夹克', category: 'outerwear', sub_category: 'bomber', color: '#1A1A1A', color_group: 'dark', material: '尼龙', pattern: null, fit: '合身', length: '短款', neckline: '翻领', detail: '翻领，前襟拉链门襟，长袖，袖口和下摆罗纹收边，两侧斜插口袋，尼龙面料轻微光泽', style_tags: ['简约', '街头'], image_url: '/openai_1780357464_553a010c.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780309117_7dd3bc18', owner_id: null, gender: 'male', name: '卡其色经典风衣', category: 'outerwear', sub_category: 'trench', color: '#C4B08A', color_group: 'warm', material: '棉', pattern: null, fit: '合身', length: '中长', neckline: '翻领', detail: '翻领，双排扣前襟，长袖，肩部有肩章装饰，腰部配有同色系腰带，防泼水棉质面料', style_tags: ['简约', '商务休闲'], image_url: '/openai_1780309117_7dd3bc18.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780444863_d9017e87', owner_id: null, gender: 'male', name: '浅蓝色牛仔夹克', category: 'outerwear', sub_category: 'jacket', color: '#A8C4D4', color_group: 'cool', material: '牛仔', pattern: '水洗磨白', fit: '合身', length: '短款', neckline: '翻领', detail: '翻领，前襟纽扣门襟，长袖袖口有纽扣开合，胸前两个翻盖口袋，下摆有调节袢扣，浅蓝水洗丹宁面料轻微磨白', style_tags: ['街头', '复古'], image_url: '/openai_1780444863_d9017e87.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1782704359_b6dc2781', owner_id: null, gender: 'male', name: '深灰色西装外套', category: 'outerwear', sub_category: 'blazer', color: '#4A4A4A', color_group: 'dark', material: '羊毛混纺', pattern: null, fit: '修身', length: '常规', neckline: '翻领', detail: '平驳领，单排两粒扣，长袖袖口四粒装饰扣，左侧胸袋，两侧翻盖口袋，后中开衩，挺括羊毛混纺面料质感', style_tags: ['简约', '通勤'], image_url: '/openai_1782704359_b6dc2781.png', layer_order: 4, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780308949_1f0b8fb2', owner_id: null, gender: 'male', name: '白色圆领短袖T恤', category: 'top', sub_category: 't_shirt', color: '#FAF7F4', color_group: 'light', material: '棉', pattern: null, fit: '合身', length: '常规', neckline: '圆领', detail: '圆领罗纹领口，落肩短袖，胸口有简约小口袋，纯棉面料轻微纹理', style_tags: ['简约'], image_url: '/openai_1780308949_1f0b8fb2.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780309158_cd03d674', owner_id: null, gender: 'male', name: '浅蓝色牛津纺衬衫', category: 'top', sub_category: 'shirt', color: '#A8C4D4', color_group: 'cool', material: '棉', pattern: null, fit: '合身', length: '常规', neckline: '翻领', detail: '翻领，前襟纽扣，长袖袖口有纽扣开合，后背有工字褶，挺括纯棉面料', style_tags: ['简约', '商务休闲'], image_url: '/openai_1780309158_cd03d674.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780309129_7c2852ff', owner_id: null, gender: 'male', name: '深蓝色Polo衫', category: 'top', sub_category: 'polo', color: '#1A3A5C', color_group: 'dark', material: '珠地网眼棉', pattern: null, fit: '合身', length: '常规', neckline: '翻领', detail: '翻领两粒扣半开襟，短袖袖口有罗纹收边，胸前有小型刺绣logo，珠地网眼棉质面料', style_tags: ['简约', '商务休闲'], image_url: '/openai_1780309129_7c2852ff.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780308997_ebeb1f9c', owner_id: null, gender: 'male', name: '灰色圆领宽松卫衣', category: 'top', sub_category: 'sweatshirt', color: '#9A9A9A', color_group: 'neutral', material: '棉', pattern: null, fit: '宽松', length: '常规', neckline: '圆领', detail: '圆领罗纹领口，落肩长袖，罗纹下摆和袖口，胸前有小印花图案，内里加绒', style_tags: ['简约', '街头'], image_url: '/openai_1780308997_ebeb1f9c.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780444759_a3b9e00a', owner_id: null, gender: 'male', name: '黑色圆领短袖T恤', category: 'top', sub_category: 't_shirt', color: '#2A2A2A', color_group: 'dark', material: '棉', pattern: null, fit: '合身', length: '常规', neckline: '圆领', detail: '圆领罗纹领口，落肩短袖，纯棉面料轻微纹理，整体简洁无印花', style_tags: ['简约'], image_url: '/openai_1780444759_a3b9e00a.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780444775_09d40d37', owner_id: null, gender: 'male', name: '燕麦色针织衫', category: 'top', sub_category: 'knit', color: '#D4C5A0', color_group: 'warm', material: '针织', pattern: null, fit: '合身', length: '常规', neckline: '圆领', detail: '圆领，长袖，罗纹领口袖口和下摆，细针针织纹理，面料柔软垂坠感', style_tags: ['简约', '商务休闲'], image_url: '/openai_1780444775_09d40d37.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1782704401_76e375bf', owner_id: null, gender: 'male', name: '黑色几何印花T恤', category: 'top', sub_category: 't_shirt', color: '#2A2A2A', color_group: 'dark', material: '棉', pattern: '胸前抽象几何图案印花', fit: '合身', length: '常规', neckline: '圆领', detail: '圆领，落肩短袖，胸前抽象几何图案印花，纯棉面料', style_tags: ['街头', '个性'], image_url: '/openai_1782704401_76e375bf.png', layer_order: 2, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780309009_4769433e', owner_id: null, gender: 'male', name: '蓝色直筒牛仔裤', category: 'bottom', sub_category: 'jeans', color: '#6B8FA3', color_group: 'cool', material: '牛仔', pattern: null, fit: '合身', length: '长款', detail: '中腰设计，直筒版型从大腿到裤脚等宽，五口袋经典结构，轻微水洗纹理，丹宁面料', style_tags: ['简约', '复古'], image_url: '/openai_1780309009_4769433e.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780309059_65ee0960', owner_id: null, gender: 'male', name: '深灰色直筒微锥西裤', category: 'bottom', sub_category: 'trousers', color: '#4A4A4A', color_group: 'dark', material: '羊毛混纺', pattern: null, fit: '合身', length: '长款', detail: '中腰直筒微锥版型，大腿至膝盖自然直筒线条，膝盖以下裤脚轻微收窄约2cm呈微锥形，非阔腿非紧身，裤腿中央有锐利熨烫折痕，侧边斜插口袋，羊毛混纺面料挺括有骨感，站立时裤脚自然盖住鞋面不堆褶', style_tags: ['简约', '通勤'], image_url: '/openai_1780309059_65ee0960.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780444788_0f4085ef', owner_id: null, gender: 'male', name: '黑色修身牛仔裤', category: 'bottom', sub_category: 'jeans', color: '#2A2A2A', color_group: 'dark', material: '牛仔', pattern: null, fit: '修身', length: '长款', detail: '中腰修身版型从大腿到脚踝微收，五口袋经典结构，黑色丹宁面料轻微水洗纹理', style_tags: ['简约', '街头'], image_url: '/openai_1780444788_0f4085ef.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780444786_018e1cbd', owner_id: null, gender: 'male', name: '卡其色斜纹休闲裤', category: 'bottom', sub_category: 'chinos', color: '#C4B08A', color_group: 'warm', material: '棉', pattern: null, fit: '合身', length: '长款', detail: '中腰直筒版型，斜纹棉布面料有细微斜向纹理，侧边斜插口袋，后臀两个嵌线口袋', style_tags: ['简约', '商务休闲'], image_url: '/openai_1780444786_018e1cbd.png', layer_order: 3, occupies_full_body: false, source: 'system' },
  { id: 'openai_1780308937_75d8daca', owner_id: null, gender: 'male', name: '深棕色乐福鞋', category: 'shoes', sub_category: 'loafers', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '学院'], image_url: '/openai_1780308937_75d8daca.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，鞋面有金属马衔扣装饰，浅口设计，平底，哑光皮面质感，鞋口边缘有细腻包边' },
  { id: 'openai_1780309138_76f0f80a', owner_id: null, gender: 'male', name: '白色皮质小白鞋', category: 'shoes', sub_category: 'sneakers', color: '#FAF7F4', color_group: 'light', material: '皮革', pattern: null, style_tags: ['简约', '运动'], image_url: '/openai_1780309138_76f0f80a.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，系带设计，橡胶鞋底侧边有纹理，白色皮革鞋面拼接，鞋头有细微透气孔' },
  { id: 'openai_1780444883_13857aa3', owner_id: null, gender: 'male', name: '深棕色德比鞋', category: 'shoes', sub_category: 'derby', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '商务休闲'], image_url: '/openai_1780444883_13857aa3.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，系带设计，开放式鞋襟，鞋底有轻微跟高，哑光皮面质感，鞋头有细微擦色' },
  { id: 'openai_1780444894_e411c5c4', owner_id: null, gender: 'male', name: '黑色切尔西靴', category: 'shoes', sub_category: 'boots', color: '#2A2A2A', color_group: 'dark', material: '皮革', pattern: null, style_tags: ['简约', '街头'], image_url: '/openai_1780444894_e411c5c4.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '尖圆头，鞋帮高至脚踝，两侧有弹性布拼接，低跟，哑光皮面质感，鞋底有轻微纹路' },
  { id: 'openai_1780308968_4cb4eef7', owner_id: null, gender: 'male', name: '深棕色托特包', category: 'bag', sub_category: 'tote', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '通勤'], image_url: '/openai_1780308968_4cb4eef7.png', layer_order: 6, occupies_full_body: false, source: 'system', detail: '敞口设计，包身方正宽大，两条长提手，素面粒纹牛皮材质，包身有细微的缝线边骨' },
  { id: 'openai_1780444877_275f1303', owner_id: null, gender: 'male', name: '棕色针扣皮带', category: 'accessory', sub_category: 'belt', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '商务休闲'], image_url: '/openai_1780444877_275f1303.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '中等宽度带身，哑光皮面质感，金色针扣，带身有均匀的缝线边骨和扣眼' },
  { id: 'openai_1782704404_856cb340', owner_id: null, gender: 'male', name: '黑色表盘腕表', category: 'accessory', sub_category: 'watch', color: '#2A2A2A', color_group: 'dark', material: '金属', pattern: null, style_tags: ['简约', '通勤'], image_url: '/openai_1782704404_856cb340.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '圆形表盘，黑色表盘上有简约刻度与指针，金属表带向外展开，表冠在右侧，表圈有细微齿轮纹' },
  { id: 'openai_1782704413_72bc0140', owner_id: null, gender: 'male', name: '深灰色棒球帽', category: 'accessory', sub_category: 'hat', color: '#4A4A4A', color_group: 'dark', material: '棉', pattern: null, style_tags: ['街头', '运动'], image_url: '/openai_1782704413_72bc0140.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '弯帽檐，帽顶六片拼接结构，帽前小型刺绣logo，后部金属调节扣，纯棉面料' },
  { id: 'openai_1782704655_0d2514a3', owner_id: null, gender: 'male', name: '黑色墨镜', category: 'accessory', sub_category: 'sunglasses', color: '#2A2A2A', color_group: 'dark', material: '塑料', pattern: null, style_tags: ['街头', '简约'], image_url: '/openai_1782704655_0d2514a3.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '方形镜框，深色镜片有轻微反光，粗板材镜腿向外展开，镜框上缘有细微金属铆钉装饰' },
  { id: 'openai_1782704668_8d5beb82', owner_id: null, gender: 'male', name: '银色项链', category: 'accessory', sub_category: 'necklace', color: '#D4D4D4', color_group: 'light', material: '金属', pattern: null, style_tags: ['街头', '个性'], image_url: '/openai_1782704668_8d5beb82.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '中等粗细链身自然弯曲盘绕，长度至锁骨以下，链身中部有方形铭牌吊坠，哑光金属质感' },

  // ===== 鞋 =====
  { id: 'openai_1780211561_10923234', owner_id: null, name: '棕色乐福鞋', category: 'shoes', sub_category: 'loafers', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '学院'], image_url: '/openai_1780211561_10923234.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，鞋面有金属马衔扣装饰，浅口设计，平底，哑光皮面质感，鞋口边缘有细腻包边' },
  { id: 'openai_1780211441_61500197', owner_id: null, name: '白色帆布小白鞋', category: 'shoes', sub_category: 'sneakers', color: '#FAF7F4', color_group: 'light', material: '帆布', pattern: null, style_tags: ['简约', '运动'], image_url: '/openai_1780211441_61500197.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，系带设计，橡胶鞋底侧边有纹理，帆布鞋面拼接，鞋头有细微橡胶包边' },
  { id: 'openai_1780211502_fecce76b', owner_id: null, name: '裸色尖头小皮鞋', category: 'shoes', sub_category: 'heels', color: '#E8C8B0', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '优雅'], image_url: '/openai_1780211502_fecce76b.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '尖头，浅口鞋面，细跟高约五厘米，哑光皮面质感，鞋口边缘有细腻包边，鞋底纤薄' },
  { id: 'openai_1780211537_53d33fdf', owner_id: null, name: '黑色玛丽珍鞋', category: 'shoes', sub_category: 'heels', color: '#2A2A2A', color_group: 'dark', material: '皮革', pattern: null, style_tags: ['复古', '甜美'], image_url: '/openai_1780211537_53d33fdf.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，脚背处有一字带搭扣，粗跟高约三厘米，亮面漆皮质感，鞋口浅口设计' },
  { id: 'openai_1780211550_68bf4634', owner_id: null, name: '黑色马丁靴', category: 'shoes', sub_category: 'boots', color: '#2A2A2A', color_group: 'dark', material: '皮革', pattern: null, style_tags: ['街头', '暗黑'], image_url: '/openai_1780211550_68bf4634.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，八孔系带，鞋帮高至脚踝以上，厚底橡胶鞋底有防滑齿纹，哑光皮面质感，鞋帮边缘有细微缝线' },
  { id: 'openai_1780211573_2b7d9ea8', owner_id: null, name: '灰白色德训鞋', category: 'shoes', sub_category: 'sneakers', color: '#E8E4DF', color_group: 'light', material: '麂皮', pattern: '灰色麂皮与白色皮革拼接', style_tags: ['复古', '运动'], image_url: '/openai_1780211573_2b7d9ea8.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，系带设计，鞋面为灰色麂皮与白色皮革拼接，生胶鞋底侧边有纹理，鞋舌上有品牌标贴' },
  { id: 'openai_1780211676_81dc82bd', owner_id: null, name: '银色玛丽珍鞋', category: 'shoes', sub_category: 'heels', color: '#D4D4D4', color_group: 'light', material: '皮革', pattern: null, style_tags: ['复古', '甜美'], image_url: '/openai_1780211676_81dc82bd.png', layer_order: 7, occupies_full_body: false, source: 'system', detail: '圆头，脚背处有一字带搭扣，粗跟高约三厘米，亮面金属银色皮质感，鞋口浅口设计' },

  // ===== 包 =====
  { id: 'openai_1780212938_9d9e3ca7', owner_id: null, name: '棕色托特包', category: 'bag', sub_category: 'tote', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '通勤'], image_url: '/openai_1780212938_9d9e3ca7.png', layer_order: 6, occupies_full_body: false, source: 'system', detail: '敞口设计，包身方正宽大，两条长提手，素面粒纹牛皮材质，包身有细微的缝线边骨' },
  { id: 'openai_1780212950_541eec4c', owner_id: null, name: '黑色链条包', category: 'bag', sub_category: 'shoulder', color: '#2A2A2A', color_group: 'dark', material: '皮革', pattern: null, style_tags: ['法式', '简约'], image_url: '/openai_1780212950_541eec4c.png', layer_order: 6, occupies_full_body: false, source: 'system', detail: '翻盖设计，金属链条肩带自然盘绕在包身旁，包身小巧方正，亮面羊皮材质，翻盖上有金属双C扣装饰' },
  { id: 'openai_1780212956_adaf4c8e', owner_id: null, name: '米白色帆布袋', category: 'bag', sub_category: 'tote', color: '#F5F0E8', color_group: 'light', material: '帆布', pattern: '简约字母印花', style_tags: ['简约', '运动'], image_url: '/openai_1780212956_adaf4c8e.png', layer_order: 6, occupies_full_body: false, source: 'system', detail: '敞口设计，包身简洁竖长，两条短提手，厚实帆布材质，包身中央有简约字母印花' },
  { id: 'openai_1780213222_4c519f72', owner_id: null, name: '金色细项链', category: 'accessory', sub_category: 'necklace', color: '#D4B060', color_group: 'warm', material: '金属', pattern: null, style_tags: ['简约', '法式'], image_url: '/openai_1780213222_4c519f72.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '锁骨链长度，链身中部有单颗小圆形吊坠，抛光金属光泽' },
  { id: 'openai_1780213231_ecf057b3', owner_id: null, name: '珍珠耳环', category: 'accessory', sub_category: 'earrings', color: '#FAF7F4', color_group: 'light', material: '珍珠', pattern: null, style_tags: ['法式', '甜美'], image_url: '/openai_1780213231_ecf057b3.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '单颗圆润珍珠镶嵌在金色耳针上，珍珠表面有柔和反光' },
  { id: 'openai_1780213253_9d455df7', owner_id: null, name: '黑色墨镜', category: 'accessory', sub_category: 'sunglasses', color: '#2A2A2A', color_group: 'dark', material: '塑料', pattern: null, style_tags: ['复古', '简约'], image_url: '/openai_1780213253_9d455df7.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '猫眼型镜框，深色镜片有反光，细金属镜腿向外展开，镜框上缘有细微的金属装饰细节' },
  { id: 'openai_1780213257_48fb6a0b', owner_id: null, name: '棕色细皮带', category: 'accessory', sub_category: 'belt', color: '#5C3A2A', color_group: 'warm', material: '皮革', pattern: null, style_tags: ['简约', '法式'], image_url: '/openai_1780213257_48fb6a0b.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '细窄带身，哑光皮面质感，金色小方扣，带身有均匀的缝线边骨，尾端收窄' },
  { id: 'openai_1780213261_a157b27f', owner_id: null, name: '玫瑰金腕表', category: 'accessory', sub_category: 'watch', color: '#D4A8A0', color_group: 'warm', material: '金属', pattern: null, style_tags: ['简约', '优雅'], image_url: '/openai_1780213261_a157b27f.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '圆形表盘，白色表盘上有简洁的刻度与指针，细金属表带向外展开，表冠在右侧，整体纤薄' },
  { id: 'openai_1780213279_26c97fd3', owner_id: null, name: '花卉图案小方巾', category: 'accessory', sub_category: 'scarf', color: '#F5F0D0', color_group: 'light', material: '丝绸', pattern: '碎花图案均匀分布', style_tags: ['法式', '复古'], image_url: '/openai_1780213279_26c97fd3.png', layer_order: 5, occupies_full_body: false, source: 'system', detail: '方形丝绸材质，边缘有手工卷边，表面分布碎花图案均匀排列，轻盈光泽感' },
  // ===== 配饰 =====
]

// 按品类分组
export function getItemsByCategory(gender?: 'male' | 'female'): Record<string, ClothingItem[]> {
  const result: Record<string, ClothingItem[]> = {
    top: [],
    bottom: [],
    dress: [],
    outerwear: [],
    shoes: [],
    bag: [],
    accessory: [],
  }
  for (const item of MOCK_CLOTHING) {
    const itemGender = item.gender || 'female'
    if (gender && itemGender !== gender) continue
    result[item.category]?.push(item)
  }
  return result
}

// 个人单品运行时缓存 — 统一注册表，合并 mock + 用户上传
const personalItemCache = new Map<string, ClothingItem>()

export function registerPersonalItems(items: ClothingItem[]) {
  for (const item of items) {
    personalItemCache.set(item.id, item)
  }
}

export function registerPersonalItem(item: ClothingItem) {
  personalItemCache.set(item.id, item)
}

export function removePersonalItem(id: string) {
  personalItemCache.delete(id)
}

export function getItemById(id: string): ClothingItem | undefined {
  return personalItemCache.get(id) || MOCK_CLOTHING.find((i) => i.id === id)
}
