/**
 * 穿搭规则库 - 身型适配规则
 * 
 * 五类身型：梨形、苹果形、沙漏形、H形、倒三角
 * 核心原则：扬长避短 — 强调优势、弱化短板
 */

import { StyleRule } from './types';

export const bodyShapeRules: StyleRule[] = [
  // ═══════════ 梨形（胯宽 > 肩宽，下半身丰满） ═══════════
  {
    id: 'body_001',
    module: 'body_shape',
    rule: '梨形上浅下深',
    desc: '梨形身材通过上浅下深将视觉重心上移到上半身。上装亮色/浅色，下装深色收缩。',
    condition: { field: '用户.身型', op: 'eq', value: '梨形' },
    type: 'prefer',
    gender: 'female',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['梨形'],
    tags: ['梨形', '色彩', '重心'],
    examples: ['白色/浅色上衣 + 黑色直筒裤'],
  },
  {
    id: 'body_002',
    module: 'body_shape',
    rule: '梨形推荐：A字裙/A字摆',
    desc: 'A字裙、A字连衣裙、阔腿裤从腰线自然散开，不贴胯不勒大腿根，是梨形最优下装。',
    condition: { field: '用户.身型', op: 'eq', value: '梨形' },
    type: 'prefer',
    gender: 'female',
    priority: 9,
    season: ['春', '夏', '秋'],
    scenes: [],
    bodyShape: ['梨形'],
    tags: ['梨形', 'A字', '下装'],
    examples: ['A字半裙 + 修身针织衫', 'A字连衣裙 + 腰带'],
  },
  {
    id: 'body_003',
    module: 'body_shape',
    rule: '梨形避免：紧身裙/铅笔裙/紧身牛仔裤',
    desc: '紧身包裹下装对梨形是大敌——直接暴露胯宽和大腿线条。直筒/阔腿/A字替代。',
    condition: [
      { field: '用户.身型', op: 'eq', value: '梨形' },
      { field: '下装', op: 'in', value: ['紧身裙', '铅笔裙', '紧身牛仔裤'] },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'female',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    sceneOverrides: [
        {
                'scene': '骑行',
                'action': 'suppress',
                'reason': '骑行裤是功能刚需，紧身包裹为安全考虑，时尚规则让路'
        },
        {
                'scene': '运动',
                'action': 'suppress',
                'reason': '运动紧身裤/瑜伽裤为功能需求，非穿搭搭配考量'
        },
        {
                'scene': '健身',
                'action': 'suppress',
                'reason': '健身紧身裤为功能性装备'
        }
],
    bodyShape: ['梨形'],
    tags: ['梨形', '避雷', '下装'],
    examples: [],
  },
  {
    id: 'body_004',
    module: 'body_shape',
    rule: '梨形强调上半身设计感',
    desc: '梨形优势在上半身——用设计感领口、泡泡袖、垫肩、项链把视线固定在上半身。',
    condition: { field: '用户.身型', op: 'eq', value: '梨形' },
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['梨形'],
    tags: ['梨形', '上半身', '设计感'],
    examples: ['泡泡袖衬衫 + 深色直筒裤', '垫肩西装 + 阔腿裤'],
  },

  // ═══════════ 苹果形（腰腹丰满，四肢偏细） ═══════════
  {
    id: 'body_005',
    module: 'body_shape',
    rule: '苹果形V领拉长颈部',
    desc: '苹果形通过V领/U领延伸颈部线条，将视线纵向下拉而非横扩。避免高领/小圆领。',
    condition: { field: '用户.身型', op: 'eq', value: '苹果形' },
    type: 'must',
    gender: 'female',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['苹果形'],
    tags: ['苹果形', '领口', '纵向线条'],
    examples: ['V领衬衫 + 直筒裤', 'V领连衣裙 + 开衫'],
  },
  {
    id: 'body_006',
    module: 'body_shape',
    rule: '苹果形避免：腰部装饰/高腰勒紧',
    desc: '苹果形避免宽腰带、腰部抽褶、高腰勒紧的单品——把注意力引向腰腹是策略错误。选自然腰线/无腰线设计。',
    condition: { field: '用户.身型', op: 'eq', value: '苹果形' },
    type: 'avoid',
    gender: 'female',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['苹果形'],
    tags: ['苹果形', '避雷', '腰部'],
    examples: [],
  },
  {
    id: 'body_007',
    module: 'body_shape',
    rule: '苹果形露腿、露手腕',
    desc: '苹果形的优势是通常四肢纤细——露手腕（挽袖口、七分袖）、露小腿（及膝裙/中裤）转移注意力。',
    condition: { field: '用户.身型', op: 'eq', value: '苹果形' },
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '夏', '秋'],
    scenes: [],
    bodyShape: ['苹果形'],
    tags: ['苹果形', '露肤', '转移注意力'],
    examples: ['七分袖连衣裙', '及膝A字裙 + 长袖上衣'],
  },

  // ═══════════ 沙漏形（肩≈胯，腰细，曲线明显） ═══════════
  {
    id: 'body_008',
    module: 'body_shape',
    rule: '沙漏形强调腰线',
    desc: '沙漏形最大优势是腰臀比——用腰带、收腰设计、高腰下装把腰线做出来。腰线是沙漏形的灵魂。',
    condition: { field: '用户.身型', op: 'eq', value: '沙漏形' },
    type: 'must',
    gender: 'female',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['沙漏形'],
    tags: ['沙漏形', '腰线', '曲线'],
    examples: ['收腰连衣裙 + 细腰带', '高腰半裙 + 塞衣角衬衫'],
  },
  {
    id: 'body_009',
    module: 'body_shape',
    rule: '沙漏形避免：oversized/无腰线单品',
    desc: 'oversized/直筒/娃娃裙等无腰线单品埋没沙漏形的最大优势。穿了等于白费身材。',
    condition: { field: '用户.身型', op: 'eq', value: '沙漏形' },
    type: 'avoid',
    gender: 'female',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['沙漏形'],
    tags: ['沙漏形', '避雷', '腰线'],
    examples: [],
  },

  // ═══════════ H形（肩、腰、胯宽度接近，无明显曲线） ═══════════
  {
    id: 'body_010',
    module: 'body_shape',
    rule: 'H形制造腰线错觉',
    desc: 'H形通过廓形对比（扩肩+扩胯、中间收腰）制造视错腰线。可用垫肩+阔摆裙、X型连衣裙实现。',
    condition: { field: '用户.身型', op: 'eq', value: 'H形' },
    type: 'prefer',
    gender: 'female',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['H形'],
    tags: ['H形', '腰线', '廓形'],
    examples: ['泡泡袖上衣 + A字裙', 'X型收腰连衣裙'],
  },
  {
    id: 'body_011',
    module: 'body_shape',
    rule: 'H形友好：直筒/oversized 走中性风',
    desc: 'H形驾驭中性、极简、oversized风格有天然优势。不走曲线路线就走质感路线——高级感是H形的牌。',
    condition: { field: '用户.身型', op: 'eq', value: 'H形' },
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '秋', '冬'],
    scenes: [],
    bodyShape: ['H形'],
    tags: ['H形', '中性', '极简', '高级感'],
    examples: ['oversized白衬衫 + 直筒西裤', '极简大衣 + 阔腿裤'],
  },

  // ═══════════ 倒三角（肩宽 > 胯宽，上半身壮） ═══════════
  {
    id: 'body_012',
    module: 'body_shape',
    rule: '倒三角上深下浅',
    desc: '倒三角与梨形反向策略——上装深色收缩肩部，下装浅色/亮色增加下半身体量，平衡上下。',
    condition: { field: '用户.身型', op: 'eq', value: '倒三角' },
    type: 'prefer',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['倒三角'],
    tags: ['倒三角', '色彩', '平衡'],
    examples: ['深色上衣 + 浅色/亮色阔腿裤'],
  },
  {
    id: 'body_013',
    module: 'body_shape',
    rule: '倒三角回避：垫肩/泡泡袖/横向条纹上装',
    desc: '倒三角上装避免垫肩、泡泡袖、船领、横向条纹——这些元素进一步扩肩。选V领、插肩袖、落肩款来削弱肩部。',
    condition: { field: '用户.身型', op: 'eq', value: '倒三角' },
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['倒三角'],
    tags: ['倒三角', '避雷', '肩部'],
    examples: [],
  },
  {
    id: 'body_014',
    module: 'body_shape',
    rule: '倒三角下装加体积',
    desc: '倒三角用阔腿裤/百褶裙/A字裙/工装裤给下半身加体积，平衡宽肩。',
    condition: { field: '用户.身型', op: 'eq', value: '倒三角' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    bodyShape: ['倒三角'],
    tags: ['倒三角', '下装', '平衡'],
    examples: ['深色修身T + 卡其阔腿裤', '藏蓝毛衣 + 白色百褶裙'],
  },

  // ═══════════ 通用身型规则 ═══════════
  {
    id: 'body_015',
    module: 'body_shape',
    rule: '所有身型避免全身紧身（除非健身场景）',
    desc: '全身紧身对所有身型都不友好（沙漏形除外但仍有风险）。日常穿搭至少留一件宽松单品。',
    condition: { field: '全身.版型', op: 'eq', value: '全部紧身' },
    type: 'avoid',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    sceneOverrides: [
        {
                'scene': '运动',
                'action': 'suppress',
                'reason': '运动/骑行全身紧身是功能需求（减少风阻/肌肉支撑）'
        },
        {
                'scene': '骑行',
                'action': 'suppress',
                'reason': '骑行服全身紧身为专业需求'
        },
        {
                'scene': '健身',
                'action': 'suppress',
                'reason': '健身服全身紧身为功能需求'
        }
],
    tags: ['通用', '版型', '避雷'],
    examples: [],
  },
  {
    id: 'body_016',
    module: 'body_shape',
    rule: '微胖/丰满→垂坠感面料',
    desc: '微胖或丰满体型选垂坠感好的面料（真丝、三醋酸、人丝、精纺羊毛），避免硬挺/膨胀感面料（硬牛仔、粗花呢、太空棉）。',
    condition: { field: '用户.体型', op: 'eq', value: '丰满' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['丰满', '面料', '垂坠'],
    examples: ['垂坠感衬衫 + 直筒西裤', '真丝连衣裙'],
  },
];
