/**
 * 穿搭规则库 - 色彩搭配规则
 * 
 * 理论基础：伊顿色环、PCCS色彩体系
 * 核心原则：色相环关系、明度对比、饱和度协调、"全身不超过3色"
 */

import { StyleRule } from './types';

export const colorRules: StyleRule[] = [
  // ═══════════ 同色系搭配 ═══════════
  {
    id: 'color_001',
    module: 'color',
    rule: '全身同色系渐变',
    desc: '同一色相不同明度/饱和度的单品组合，营造高级层次感。最安全的搭配策略。',
    condition: [
      { field: '上装.颜色.色系', op: 'eq', value: '可设定' },
      { field: '下装.颜色.色系', op: 'eq', value: '与上装同色系' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['同色系', '高级感', '基础搭配'],
    examples: [
      '米白衬衫 + 奶油白西裤',
      '藏蓝衬衫 + 浅蓝牛仔裤',
      '卡其风衣 + 深棕西裤 + 米白毛衣',
      '灰色大衣 + 浅灰高领毛衣 + 深灰西裤',
    ],
  },
  {
    id: 'color_002',
    module: 'color',
    rule: '同色系不同材质',
    desc: '同一色系但材质质感不同，打破单调。光泽材质+哑光材质组合最佳。',
    condition: [
      { field: '上装.颜色.色系', op: 'eq', value: '与下装同色系' },
      { field: '上装.材质', op: 'neq', value: '与下装材质相同' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['同色系', '材质混搭', '质感'],
    examples: [
      '真丝衬衫 + 羊毛西裤（同色不同质感）',
      '棉质T恤 + 牛仔下装',
      '针织毛衣 + 皮质半裙',
    ],
  },

  // ═══════════ 邻近色搭配 ═══════════
  {
    id: 'color_003',
    module: 'color',
    rule: '邻近色过渡',
    desc: '色环上相邻的色相搭配（30°以内），柔和协调。比同色系更有层次，比撞色更安全。',
    condition: [
      { field: '上装.颜色.色相', op: 'in', value: ['邻近色关系'] },
      { field: '下装.颜色.色相', op: 'in', value: ['邻近色关系'] },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['邻近色', '柔和', '协调'],
    examples: [
      '鹅黄衬衫 + 奶油白西裤',
      '浅蓝衬衫 + 灰蓝牛仔裤',
      '豆绿上衣 + 米色半裙',
      '藕粉毛衣 + 裸色西裤',
    ],
  },

  // ═══════════ 中性色搭配 ═══════════
  {
    id: 'color_004',
    module: 'color',
    rule: '中性色万能原则',
    desc: '黑、白、灰、米、卡其、藏蓝——与任何颜色搭配均无风险。一身至少1件中性色单品。',
    condition: { field: '全身.至少一件.颜色.色系', op: 'in', value: ['中性色'] },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['中性色', '安全', '万能'],
    examples: [
      '彩色毛衣 + 黑色西装裤',
      '碎花裙 + 米色开衫',
      '亮色卫衣 + 白色牛仔裤',
    ],
  },
  {
    id: 'color_005',
    module: 'color',
    rule: 'All Black 全黑搭配',
    desc: '全身黑色需要材质对比来破沉闷。不同质感的黑色叠穿（皮革+棉+针织+纱）。男女通用。',
    condition: [
      { field: '上装.颜色', op: 'eq', value: '黑色' },
      { field: '下装.颜色', op: 'eq', value: '黑色' },
      { field: '外套.颜色', op: 'eq', value: '黑色' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '秋', '冬'],
    scenes: [],
    tags: ['全黑', '材质对比', '酷感'],
    examples: [
      '皮夹克 + 棉质黑T + 黑牛仔',
      '黑西裝外套 + 真丝黑衬衫 + 黑西裤',
    ],
  },
  {
    id: 'color_006',
    module: 'color',
    rule: 'All White 全白搭配',
    desc: '全身白色需要版型和材质变化避免单调。不同白度（米白/纯白/灰白）层次叠加。',
    condition: { field: '全身.颜色', op: 'in', value: ['白色系'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['春', '夏'],
    scenes: [],
    tags: ['全白', '清新', '层次'],
    examples: [
      '米白亚麻衬衫 + 纯白阔腿裤',
      'oversized白衬衫 + 奶油白直筒裤',
    ],
  },

  // ═══════════ 撞色/互补色搭配 ═══════════
  {
    id: 'color_007',
    module: 'color',
    rule: '一点亮色原则',
    desc: '全身中性色为基底，仅1件单品用亮色/彩色作为视觉焦点。面积比约80:20。',
    condition: [
      { field: '全身.彩色单品数量', op: 'eq', value: '1' },
      { field: '全身.中性色单品数量', op: 'between', value: ['2', '4'] },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['亮色', '焦点', '点缀'],
    examples: [
      '全黑穿搭 + 红色手袋',
      '白T+牛仔裤 + 亮黄西装外套',
      '藏蓝一身 + 橙色围巾',
    ],
  },
  {
    id: 'color_008',
    module: 'color',
    rule: '互补色撞色',
    desc: '色环上完全相对的颜色（180°），冲击力强。适合上装/外套与配饰之间小面积撞色，不建议大面积使用。',
    condition: { field: '搭配.撞色面积比', op: 'between', value: ['1:3', '1:5'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 5,
    season: ['春', '夏', '秋'],
    scenes: [],
    tags: ['撞色', '互补色', '大胆', '配饰'],
    examples: [
      '蓝色衬衫 + 橙色丝巾',
      '紫色上衣 + 黄色手袋',
      '红裙 + 绿色耳饰',
    ],
  },
  {
    id: 'color_009',
    module: 'color',
    rule: '避免大面积极端撞色',
    desc: '红配绿、紫配黄等互补色大面积使用极易翻车。如执意使用，一方降低饱和度或改为配饰。',
    condition: [
      { field: '上装.颜色.色相', op: 'in', value: ['互补色关系'] },
      { field: '下装.颜色.色相', op: 'in', value: ['互补色关系'] },
      { field: '搭配.饱和度和', op: 'eq', value: '双高饱和' },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['撞色', '避雷', '互补色'],
    examples: [
      '高饱和红色卫衣 + 高饱和绿色裤子 → 改为红卫衣 + 黑色裤',
    ],
  },

  // ═══════════ 饱和度规则 ═══════════
  {
    id: 'color_010',
    module: 'color',
    rule: '饱和度和不超过2件高饱和单品',
    desc: '一身高饱和单品不超过2件。1件亮色+其余低饱和或中性色是安全线。',
    condition: { field: '全身.高饱和单品数量', op: 'between', value: ['0', '2'] },
    type: 'must',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['饱和度', '平衡'],
    examples: [],
  },
  {
    id: 'color_011',
    module: 'color',
    rule: '低饱和莫兰迪色系',
    desc: '加入灰调的莫兰迪色系（灰粉、灰蓝、灰绿、燕麦色等），百搭不挑人，温柔高级。',
    condition: { field: '全身.颜色.饱和度', op: 'in', value: ['低饱和'] },
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '秋', '冬'],
    scenes: [],
    tags: ['莫兰迪', '低饱和', '温柔', '高级感'],
    examples: [
      '灰粉毛衣 + 燕麦色西裤',
      '灰蓝衬衫 + 米白半裙',
    ],
  },

  // ═══════════ 明度规则 ═══════════
  {
    id: 'color_012',
    module: 'color',
    rule: '上浅下深',
    desc: '上装浅色、下装深色——视觉重心下沉，显高显稳。通用搭配铁律。',
    condition: [
      { field: '上装.颜色.明度', op: 'eq', value: '高' },
      { field: '下装.颜色.明度', op: 'eq', value: '低' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['明度', '显高', '经典'],
    examples: [
      '白衬衫 + 黑西裤',
      '浅蓝衬衫 + 深蓝牛仔',
      '米色毛衣 + 深棕半裙',
    ],
  },
  {
    id: 'color_013',
    module: 'color',
    rule: '上深下浅（法式优雅）',
    desc: '上装深色、下装浅色——时髦感更强，适合肤色偏白、风格偏法式/日系的人群。对下半身比例要求高。',
    condition: [
      { field: '上装.颜色.明度', op: 'eq', value: '低' },
      { field: '下装.颜色.明度', op: 'eq', value: '高' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['春', '夏', '秋'],
    scenes: [],
    tags: ['明度', '法式', '反常规', '时髦'],
    examples: [
      '藏蓝毛衣 + 白色阔腿裤',
      '黑色修身T + 卡其半裙',
    ],
  },
  {
    id: 'color_014',
    module: 'color',
    rule: '内浅外深（外套层次）',
    desc: '内搭浅色 + 外套深色，领口/袖口浅色露出增加层次，视觉收缩显瘦。',
    condition: [
      { field: '内搭.颜色.明度', op: 'eq', value: '高' },
      { field: '外套.颜色.明度', op: 'eq', value: '低' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['秋', '冬'],
    scenes: [],
    tags: ['明度', '外套', '层次', '显瘦'],
    examples: [
      '白色内搭T + 黑色西装外套',
      '米色高领毛衣 + 深灰大衣',
    ],
  },

  // ═══════════ 三色法则 ═══════════
  {
    id: 'color_015',
    module: 'color',
    rule: '全身不超过3个色块',
    desc: '全身颜色（不含黑/白/灰/牛仔本色）不超过3个色块。超过3色需要降低饱和度或缩小面积平衡。这是穿搭最基本的色彩纪律。',
    condition: { field: '全身.色块数量', op: 'between', value: ['1', '3'] },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['三色法则', '基础', '纪律'],
    examples: [],
  },
  {
    id: 'color_016',
    module: 'color',
    rule: '鞋包同色或呼应',
    desc: '鞋子和包/腰带的颜色一致或呼应，能让整体穿搭看起来"用心了"。颜色呼应不必完全一致，同色系即可。',
    condition: [
      { field: '鞋子.颜色.色系', op: 'eq', value: '与包同色系' },
    ],
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['鞋包呼应', '细节', '完成度'],
    examples: [
      '棕色乐福鞋 + 棕色托特包',
      '黑色短靴 + 黑色斜挎包',
      '奶茶色运动鞋 + 米色帆布包',
    ],
  },

  // ═══════════ 肤色适配 ═══════════
  {
    id: 'color_017',
    module: 'color',
    rule: '暖黄皮避免冷调高饱和',
    desc: '偏暖/偏黄肤色避免荧光粉、冷调蓝、亮紫等冷调高饱和色直接贴脸。如需使用，移到下装或配饰。',
    condition: [
      { field: '上装.颜色', op: 'in', value: ['冷调高饱和色'] },
      { field: '用户.肤色', op: 'eq', value: '暖黄皮' },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['肤色', '显白', '避雷'],
    examples: [],
  },
  {
    id: 'color_018',
    module: 'color',
    rule: '暖黄皮推荐色',
    desc: '暖黄皮友好色：豆沙粉、砖红、姜黄、橄榄绿、奶茶色、燕麦色、奶油白。这些色系贴脸显白。',
    condition: { field: '用户.肤色', op: 'eq', value: '暖黄皮' },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['肤色', '显白', '暖黄皮'],
    examples: ['豆沙粉毛衣 + 奶油白裤', '橄榄绿衬衫 + 米色半裙'],
  },
  {
    id: 'color_019',
    module: 'color',
    rule: '冷白皮推荐色',
    desc: '冷白皮友好色：宝石蓝、酒红、玫红、藏蓝、正红。冷调高饱和色在冷白皮身上不突兀反而出彩。',
    condition: { field: '用户.肤色', op: 'eq', value: '冷白皮' },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['肤色', '冷白皮'],
    examples: ['宝石蓝衬衫 + 白裤', '酒红连衣裙 + 黑色高跟鞋'],
  },

  // ═══════════ 季节色板 ═══════════
  {
    id: 'color_020',
    module: 'color',
    rule: '春夏色板偏好',
    desc: '春夏适用浅色、亮色、马卡龙色、粉彩色系。材质配合轻薄面料。',
    condition: { field: '季节', op: 'in', value: ['春', '夏'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['春', '夏'],
    scenes: [],
    tags: ['季节', '春夏', '清新'],
    examples: ['浅黄衬衫 + 白直筒裤', '粉蓝连衣裙 + 米色凉鞋'],
  },
  {
    id: 'color_021',
    module: 'color',
    rule: '秋冬色板偏好',
    desc: '秋冬适用深色、大地色、复古色系（酒红、藏蓝、焦糖、橄榄绿）。材质配合羊毛/绒/皮革。',
    condition: { field: '季节', op: 'in', value: ['秋', '冬'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['秋', '冬'],
    scenes: [],
    tags: ['季节', '秋冬', '大地色'],
    examples: ['焦糖色大衣 + 藏蓝毛衣 + 深灰裤', '酒红毛衣 + 深蓝牛仔'],
  },

  // ═══════════ 男生专属 ═══════════
  {
    id: 'color_022',
    module: 'color',
    rule: '男生上装彩色下装中性',
    desc: '男生彩色单品优先放上半身（外套/卫衣/衬衫），下装保持中性色或牛仔。视觉重心自然落在面部附近。',
    condition: { field: '男生.彩色单品', op: 'eq', value: '上装或外套' },
    type: 'prefer',
    gender: 'male',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['男生', '色彩分布'],
    examples: ['亮色卫衣 + 黑色束脚裤', '蓝衬衫 + 卡其裤'],
  },
  {
    id: 'color_023',
    module: 'color',
    rule: '男生避免全身亮色',
    desc: '男生全身亮色/荧光色容易显浮夸。荧光色只建议在运动场景使用。',
    condition: { field: '全身.高饱和单品数量', op: 'between', value: ['3', '99'] },
    type: 'avoid',
    gender: 'male',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: [],
    tags: ['男生', '避雷', '亮色'],
    examples: [],
  },

  // ═══════════ 女生专属 ═══════════
  {
    id: 'color_024',
    module: 'color',
    rule: '女生彩色半裙/裤装提亮',
    desc: '女生彩色下装是安全又出彩的策略——上半身保持中性色，下半身用亮色，视觉重心下移不挑肤色。',
    condition: [
      { field: '上装.颜色.色系', op: 'in', value: ['中性色'] },
      { field: '下装.颜色.饱和度', op: 'eq', value: '高' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'female',
    priority: 7,
    season: ['春', '夏', '秋'],
    scenes: [],
    tags: ['女生', '彩色下装', '安全出彩'],
    examples: [
      '白衬衫 + 亮橙半裙',
      '黑色修身T + 宝石蓝阔腿裤',
    ],
  },
];
