/**
 * 穿搭规则库 - 叠穿/层次规则
 * 
 * 核心：由薄到厚、由紧到松、由内到外
 * 经典三层法：内层贴肤 + 中层造型 + 外层防护
 */

import { StyleRule } from './types';

export const layeringRules: StyleRule[] = [
  // ═══════════ 基本三层法 ═══════════
  {
    id: 'lay_001',
    module: 'layering',
    rule: '经典三层法',
    desc: '内层贴身打底（吸湿排汗）、中层造型主力（衬衫/毛衣/卫衣）、外层防护造型（外套/大衣）。三层由薄到厚、由紧到松。可灵活做减法（春=2层，深冬=3层）。',
    condition: { field: '搭配.层数', op: 'between', value: ['2', '3'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 10,
    season: ['秋', '冬', '春'],
    scenes: [],
    tags: ['叠穿', '三层法', '层次'],
    examples: [
      '打底T + 衬衫 + 大衣（3层）',
      '高领打底 + 圆领毛衣 + 风衣（3层）',
      '白T + 牛仔外套（2层春秋）',
    ],
  },
  {
    id: 'lay_002',
    module: 'layering',
    rule: '内层必须贴身/修身',
    desc: '内层宽松会导致中层鼓包、外层紧绷，三层互相打架。第一层必须修身或紧身。',
    condition: { field: '内层.版型', op: 'in', value: ['紧身', '修身'] },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['秋', '冬'],
    scenes: [],
    tags: ['叠穿', '内层', '版型'],
    examples: [],
  },

  // ═══════════ 领口层次 ═══════════
  {
    id: 'lay_003',
    module: 'layering',
    rule: '领口从高到低',
    desc: '叠穿时领口从内到外由低到高——最内圆领/V领，中层高领/衬衫领，外层可再低。反过来穿（高领内、V领外）违和。',
    condition: { field: '叠穿.领口', op: 'eq', value: '从内到外逐渐升高' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['秋', '冬'],
    scenes: [],
    tags: ['叠穿', '领口', '层次'],
    examples: [
      '圆领白T（内） + V领毛衣（中） → ❌ 反过来才对',
      'V领内搭（内） + 圆领毛衣（中）+ 翻领大衣（外） → ✅',
    ],
  },
  {
    id: 'lay_004',
    module: 'layering',
    rule: '衬衫领外翻',
    desc: '圆领毛衣/卫衣内搭衬衫时，领口、袖口、下摆各露出衬衫1-2cm做层次。preppy/学院风经典手法。',
    condition: [
      { field: '内搭', op: 'eq', value: '衬衫' },
      { field: '中层', op: 'in', value: ['圆领毛衣', '圆领卫衣', 'V领毛衣'] },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '秋', '冬'],
    scenes: [],
    tags: ['叠穿', '衬衫领', '学院风', 'preppy'],
    examples: ['白衬衫 + 藏蓝圆领毛衣，领口/袖口/下摆各露1-2cm'],
  },
  {
    id: 'lay_005',
    module: 'layering',
    rule: '高领毛衣不做中层',
    desc: '高领毛衣内搭再叠衬衫/外套容易显脖子短、局促。如做内层，外层必须敞领口（V领开衫/西装领外套）。',
    condition: [
      { field: '中层', op: 'eq', value: '高领毛衣' },
      { field: '外层.领口', op: 'in', value: ['圆领', '高领', '小翻领'] },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'unisex',
    priority: 8,
    season: ['冬'],
    scenes: [],
    tags: ['叠穿', '高领', '脖子', '避雷'],
    examples: [],
  },

  // ═══════════ 袖子层次 ═══════════
  {
    id: 'lay_006',
    module: 'layering',
    rule: '内层袖口露出',
    desc: '内搭袖口从外套袖口露出0.5-1cm，细节感是穿搭完成度的标志。衬衫内搭优先，其次是不同色的打底。',
    condition: { field: '叠穿.袖口', op: 'eq', value: '内层露出' },
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['秋', '冬', '春'],
    scenes: [],
    tags: ['叠穿', '袖口', '细节', '完成度'],
    examples: ['白衬衫袖口外露于西装外套袖口'],
  },

  // ═══════════ 下摆层次 ═══════════
  {
    id: 'lay_007',
    module: 'layering',
    rule: '下摆阶梯长度',
    desc: '叠穿时内层最短、中层适中、外层最长——形成下摆的阶梯层次，纵向延伸线条显高。',
    condition: { field: '叠穿.下摆', op: 'eq', value: '从内到外逐渐加长' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['秋', '冬', '春'],
    scenes: [],
    tags: ['叠穿', '下摆', '显高'],
    examples: [
      '打底T（短） + 衬衫（中） + 大衣（长）',
    ],
  },
  {
    id: 'lay_008',
    module: 'layering',
    rule: '避免内层长过外层',
    desc: '内搭下摆长过外套下摆显邋遢、比例失调。除非刻意营造解构感（日系/山系风格除外）。',
    condition: [
      { field: '内层.长度', op: 'in', value: ['中长', '长款'] },
      { field: '外层.长度', op: 'in', value: ['短款', '常规'] },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'unisex',
    priority: 8,
    season: ['春', '秋', '冬'],
    scenes: [],
    tags: ['叠穿', '下摆', '比例', '避雷'],
    examples: [],
    conflicts: ['lay_009'],
  },
  {
    id: 'lay_009',
    module: 'layering',
    rule: '长内搭+短外套 = 日系解构例外',
    desc: '日系/山系风格允许长款内搭（长T/长衬衫）外搭短款外套作为解构手法。但仅限特定风格，非通用规则。',
    condition: [
      { field: '风格', op: 'in', value: ['日系', '山系', '街头'] },
      { field: '内层.长度', op: 'in', value: ['中长', '长款'] },
      { field: '外层.长度', op: 'in', value: ['短款', '常规'] },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['春', '秋'],
    scenes: [],
    tags: ['叠穿', '日系', '解构', '例外'],
    examples: ['oversized长T + 短款夹克'],
    conflicts: ['lay_008'],
  },

  // ═══════════ 材质叠穿 ═══════════
  {
    id: 'lay_010',
    module: 'layering',
    rule: '不同材质叠加 > 同材质叠加',
    desc: '同材质叠穿（棉+棉+棉）层次感弱，不同材质（棉+羊毛+尼龙/皮质）质感对比强烈，层次分明。',
    condition: { field: '叠穿.材质种类', op: 'between', value: ['2', '3'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['秋', '冬'],
    scenes: [],
    tags: ['叠穿', '材质', '质感'],
    examples: [
      '棉T + 羊毛毛衣 + 尼龙羽绒服',
      '真丝衬衫 + 羊毛开衫 + 棉质风衣',
    ],
  },

  // ═══════════ 男生叠穿 ═══════════
  {
    id: 'lay_011',
    module: 'layering',
    rule: '男生T恤+衬衫敞穿',
    desc: '男生最基础叠穿：纯色T（内）+ 衬衫敞着穿（外），袖子卷起。春夏秋三季通用，出错率零。',
    condition: { field: '性别', op: 'eq', value: 'male' },
    type: 'prefer',
    gender: 'male',
    priority: 8,
    season: ['春', '夏', '秋'],
    scenes: [],
    tags: ['男生', '叠穿', '基础'],
    examples: ['白T + 蓝牛仔衬衫敞开 + 卡其裤', '黑T + 格子衬衫敞开 + 黑牛仔裤'],
  },
  {
    id: 'lay_012',
    module: 'layering',
    rule: '男生卫衣+大衣混搭',
    desc: '男生卫衣（休闲）+ 大衣/风衣（正式）混搭 = effortless chic。卫衣不要太厚，颜色低调。',
    condition: [
      { field: '内层', op: 'in', value: ['卫衣', '圆领毛衣'] },
      { field: '外层', op: 'in', value: ['大衣', '风衣'] },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'male',
    priority: 7,
    season: ['秋', '冬'],
    scenes: [],
    tags: ['男生', '混搭', '大衣'],
    examples: ['灰色卫衣 + 驼色大衣 + 牛仔裤 + 短靴'],
  },

  // ═══════════ 女生叠穿 ═══════════
  {
    id: 'lay_013',
    module: 'layering',
    rule: '女生吊带裙+T恤叠穿',
    desc: '细吊带连衣裙内搭修身T恤/高领打底，让夏日吊带裙穿到春秋，一衣多穿。',
    condition: [
      { field: '外层', op: 'in', value: ['吊带裙'] },
      { field: '内层', op: 'in', value: ['T恤', '高领打底'] },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'female',
    priority: 7,
    season: ['春', '秋', '冬'],
    scenes: [],
    tags: ['女生', '叠穿', '一衣多穿'],
    examples: ['白T + 碎花吊带裙', '黑色高领打底 + 真丝吊带裙'],
  },
  {
    id: 'lay_014',
    module: 'layering',
    rule: '女生西装外套+连衣裙',
    desc: '修身连衣裙外搭宽松西装外套，柔美+利落混搭。约会/通勤一键切换。',
    condition: [
      { field: '内层', op: 'eq', value: '连衣裙' },
      { field: '外层', op: 'eq', value: '西装外套' },
    ],
    conditionLogic: 'AND',
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '秋'],
    scenes: [],
    tags: ['女生', '混搭', '西装'],
    examples: ['真丝连衣裙 + oversized西装外套 + 短靴'],
  },
];
