/**
 * 穿搭规则库 - 场景/场合规则
 * 
 * 场景 → 必须包含 / 建议 / 避免 的穿搭要素
 */

import { StyleRule, Scene } from './types';

/** 运动类场景 */
const SPORT_SCENES: Scene[] = ['运动', '健身', '户外', '徒步', '骑行'];
/** 正式场景 */
const FORMAL_SCENES: Scene[] = ['面试', '正式商务', '晚宴', '酒会'];
/** 休闲场景 */
const CASUAL_SCENES: Scene[] = ['日常休闲', '周末', '逛街'];
/** 通勤场景 */
const COMMUTE_SCENES: Scene[] = ['职场通勤'];
/** 社交场景 */
const SOCIAL_SCENES: Scene[] = ['约会', '派对'];
/** 度假场景 */
const VACATION_SCENES: Scene[] = ['度假', '旅行', '海边', '城市旅行'];
/** 轻社交场景 */
const BRUNCH_SCENES: Scene[] = ['周末brunch'];
/** 独处场景 */
const SOLO_SCENES: Scene[] = ['书店咖啡馆独处'];
/** 高社交压力场景 */
const EX_SCENES: Scene[] = ['前男友聚会'];

export const occasionRules: StyleRule[] = [
  // ═══════════ 职场通勤 ═══════════
  {
    id: 'occ_001',
    module: 'occasion',
    rule: '通勤标配：有领上衣',
    desc: '职场场景至少一件有领单品（衬衫/西装领/小翻领）。Polo衫为下限，T恤仅限创意/互联网公司。',
    condition: { field: '场景', op: 'eq', value: '职场通勤' },
    type: 'prefer',
    gender: 'unisex',
    priority: 9,
    season: ['春', '秋', '冬'],
    scenes: COMMUTE_SCENES,
    tags: ['通勤', '职场', '得体'],
    examples: ['衬衫 + 西裤 + 乐福鞋', '西装外套 + 圆领毛衣（内搭衬衫领）'],
  },
  {
    id: 'occ_002',
    module: 'occasion',
    rule: '通勤禁拖鞋/运动凉鞋',
    desc: '职场通勤避免拖鞋、运动凉鞋、人字拖。夏季可选包头凉鞋、穆勒鞋、乐福鞋作为替代。',
    condition: [
      { field: '场景', op: 'eq', value: '职场通勤' },
      { field: '鞋', op: 'in', value: ['拖鞋', '人字拖', '运动凉鞋'] },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['夏'],
    scenes: COMMUTE_SCENES,
    tags: ['通勤', '职场', '鞋', '避雷'],
    examples: [],
  },
  {
    id: 'occ_003',
    module: 'occasion',
    rule: '通勤推荐色系',
    desc: '职场通勤推荐低饱和色系：藏蓝、深灰、炭灰、米白、卡其、黑。避免大面积荧光色、碎花、卡通图案。',
    condition: { field: '场景', op: 'eq', value: '职场通勤' },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: COMMUTE_SCENES,
    tags: ['通勤', '职场', '色彩'],
    examples: [],
  },
  {
    id: 'occ_004',
    module: 'occasion',
    rule: '通勤男生套装公式',
    desc: '衬衫（白色/浅蓝）+ 西裤/深色牛仔裤 + 乐福鞋/牛津鞋 + 腰带 + 手表。春夏可去外套。',
    condition: { field: '场景', op: 'eq', value: '职场通勤' },
    type: 'prefer',
    gender: 'male',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: COMMUTE_SCENES,
    tags: ['通勤', '男生', '套装'],
    examples: ['白衬衫 + 炭灰西裤 + 棕色乐福鞋 + 手表'],
  },
  {
    id: 'occ_005',
    module: 'occasion',
    rule: '通勤女生套装公式',
    desc: '衬衫/针织衫 + 西裤/半裙/连衣裙 + 乐福鞋/低跟鞋/平底鞋 + 托特包。可加西装外套做层次。',
    condition: { field: '场景', op: 'eq', value: '职场通勤' },
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: COMMUTE_SCENES,
    tags: ['通勤', '女生', '套装'],
    examples: ['真丝衬衫 + 阔腿西裤 + 尖头低跟鞋 + 托特包'],
  },

  // ═══════════ 面试/正式场合 ═══════════
  {
    id: 'occ_006',
    module: 'occasion',
    rule: '面试穿西装',
    desc: '面试/重要商务会议：成套西装或西装外套+西裤/半裙，正式度最高。颜色藏蓝>深灰>黑。',
    condition: { field: '场景', op: 'in', value: ['面试', '正式商务'] },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['春', '秋', '冬'],
    scenes: ['面试', '正式商务'],
    tags: ['面试', '正式', '西装'],
    examples: ['藏蓝西装套装 + 白衬衫 + 牛津鞋'],
  },
  {
    id: 'occ_007',
    module: 'occasion',
    rule: '面试避免：牛仔/运动鞋/卫衣',
    desc: '面试场合禁止牛仔裤、运动鞋、卫衣、短裤、拖鞋。任何一件运动/休闲单品即拉低正式度。',
    condition: { field: '场景', op: 'in', value: ['面试', '正式商务'] },
    type: 'avoid',
    gender: 'unisex',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['面试', '正式商务'],
    tags: ['面试', '避雷'],
    examples: [],
  },

  // ═══════════ 约会 ═══════════
  {
    id: 'occ_008',
    module: 'occasion',
    rule: '约会男生 smart casual 底线',
    desc: '约会场景至少 smart casual：有领上衣（衬衫/Polo/质感好的针织）+ 修身/合身裤 + 非运动鞋。干净 > 潮。',
    condition: { field: '场景', op: 'in', value: ['约会'] },
    type: 'must',
    gender: 'male',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['约会'],
    tags: ['约会', '男生', '得体'],
    examples: ['亚麻衬衫 + 修身牛仔裤 + 乐福鞋', '质感针织衫 + 直筒休闲裤 + 皮质小白鞋'],
  },
  {
    id: 'occ_009',
    module: 'occasion',
    rule: '约会男生避免',
    desc: '约会男生避免：全套运动装、篮球鞋、人字拖、过于肥大的衣服、过多logo印花。',
    condition: { field: '场景', op: 'in', value: ['约会'] },
    type: 'avoid',
    gender: 'male',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['约会'],
    tags: ['约会', '男生', '避雷'],
    examples: [],
  },
  {
    id: 'occ_010',
    module: 'occasion',
    rule: '约会女生推荐连衣裙/半裙',
    desc: '约会优先连衣裙或半裙，比裤子更有女性气质。长度膝盖上下为黄金区间。',
    condition: { field: '场景', op: 'in', value: ['约会'] },
    type: 'prefer',
    gender: 'female',
    priority: 8,
    season: ['春', '夏', '秋'],
    scenes: ['约会'],
    tags: ['约会', '女生', '裙装', '甜美'],
    examples: ['碎花连衣裙 + 平底凉鞋', '吊带连衣裙 + 开衫 + 小猫跟'],
  },
  {
    id: 'occ_011',
    module: 'occasion',
    rule: '约会选一件"小心机"单品',
    desc: '约会穿搭留一个亮点：特别的首饰、质感好的包、好看的鞋子、一抹亮色。不必全身都用力。',
    condition: { field: '场景', op: 'in', value: ['约会'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['约会', '派对'],
    tags: ['约会', '小心机', '亮点', '甜美'],
    examples: ['简约穿搭 + 一条特别项链', '基础色一身 + 红色小包'],
  },

  // ═══════════ 晩宴/酒会 ═══════════
  {
    id: 'occ_012',
    module: 'occasion',
    rule: '晩宴/酒会光泽面料',
    desc: '正式晚宴：真丝、缎面、丝绒等光泽面料提升正式度和华丽感。日常棉麻不适用。',
    condition: { field: '场景', op: 'in', value: ['晚宴', '酒会', '派对'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['晚宴', '酒会', '派对'],
    tags: ['晚宴', '面料', '正式'],
    examples: ['真丝连衣裙 + 高跟鞋', '丝绒西装外套 + 衬衫 + 西裤'],
  },
  {
    id: 'occ_013',
    module: 'occasion',
    rule: '晩宴女生礼服/连衣裙',
    desc: '晚宴/酒会女生穿连衣裙（及膝或更长）或上下装分开但材质统一。面料光泽、剪裁修身。',
    condition: { field: '场景', op: 'in', value: ['晚宴', '酒会'] },
    type: 'must',
    gender: 'female',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['晚宴', '酒会'],
    tags: ['晚宴', '女生', '礼服'],
    examples: ['真丝长裙 + 细高跟 + 手拿包'],
  },
  {
    id: 'occ_014',
    module: 'occasion',
    rule: '晩宴男生西装+皮鞋',
    desc: '晚宴男生穿西装套装或西装外套+西裤，搭配牛津鞋/德比鞋。领带/领结视dress code。',
    condition: { field: '场景', op: 'in', value: ['晚宴', '酒会'] },
    type: 'must',
    gender: 'male',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: ['晚宴', '酒会'],
    tags: ['晚宴', '男生', '西装'],
    examples: ['深色西装 + 白衬衫 + 牛津鞋'],
  },

  // ═══════════ 休闲日常 ═══════════
  {
    id: 'occ_015',
    module: 'occasion',
    rule: '日常休闲不设限',
    desc: '日常休闲/周末/逛街场景无硬性着装要求，以舒适+个人风格为主。但至少保持整洁。',
    condition: { field: '场景', op: 'in', value: ['日常休闲', '周末', '逛街'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 5,
    season: ['春', '夏', '秋', '冬'],
    scenes: CASUAL_SCENES,
    tags: ['休闲', '日常'],
    examples: [],
  },
  {
    id: 'occ_016',
    module: 'occasion',
    rule: '休闲日系/韩系叠穿',
    desc: '休闲场景可选日系/韩系叠穿法：基础款 + 多个层次（打底+衬衫+开衫）。注意颜色控制在低饱和。',
    condition: { field: '场景', op: 'in', value: ['日常休闲', '周末'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 6,
    season: ['春', '秋', '冬'],
    scenes: CASUAL_SCENES,
    tags: ['休闲', '日系', '韩系', '叠穿'],
    examples: [
      '白T + 格子衬衫敞开 + 针织开衫 + 直筒牛仔裤',
      '高领打底 + 圆领卫衣 + 大衣',
    ],
  },

  // ═══════════ 运动/户外 ═══════════
  {
    id: 'occ_017',
    module: 'occasion',
    rule: '运动场景功能优先',
    desc: '运动/健身/户外场景以功能性面料为主（速干/透气/防水）。搭配考量从功能出发，不必追求视觉效果。',
    condition: { field: '场景', op: 'in', value: ['运动', '健身', '户外', '徒步'] },
    type: 'must',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: SPORT_SCENES,
    tags: ['运动', '户外', '功能'],
    examples: [],
  },
  {
    id: 'occ_018',
    module: 'occasion',
    rule: '运动鞋只在运动场景',
    desc: '专业跑步鞋/训练鞋只匹配运动场景。日常穿搭选板鞋/复古跑鞋/帆布鞋，而非明显功能型运动鞋。',
    condition: [
      { field: '场景', op: 'not_in', value: ['运动', '健身', '户外'] },
      { field: '鞋', op: 'in', value: ['专业跑鞋', '训练鞋'] },
    ],
    conditionLogic: 'AND',
    type: 'avoid',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: CASUAL_SCENES,
    tags: ['运动鞋', '场景匹配', '避雷'],
    examples: [],
  },

  // ═══════════ 度假/旅行 ═══════════
  {
    id: 'occ_019',
    module: 'occasion',
    rule: '度假亮色/印花放开',
    desc: '度假/旅行场景可以大胆使用亮色、印花、碎花、度假风单品（草帽/编织包/凉拖）。日常不敢穿的这时候穿。',
    condition: { field: '场景', op: 'in', value: ['度假', '旅行', '海边'] },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏'],
    scenes: VACATION_SCENES,
    tags: ['度假', '亮色', '印花', '放松'],
    examples: ['碎花连衣裙 + 草帽 + 编织包 + 凉拖'],
  },
  {
    id: 'occ_020',
    module: 'occasion',
    rule: '城市旅行舒适与出片平衡',
    desc: '城市旅行穿搭兼顾走路舒适（平底鞋/运动鞋/低跟鞋）和上镜需求（色彩/层次/配饰）。选一双好看又舒服的鞋是关键。',
    condition: { field: '场景', op: 'eq', value: '城市旅行' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '秋'],
    scenes: ['城市旅行'],
    sceneOverrides: [
        {
                'scene': '骑行',
                'action': 'suppress',
                'reason': '骑行锁鞋/运动鞋为安全刚需'
        },
        {
                'scene': '运动',
                'action': 'suppress',
                'reason': '运动场景专业运动鞋为刚需'
        },
        {
                'scene': '健身',
                'action': 'suppress',
                'reason': '健身场景训练鞋为刚需'
        },
        {
                'scene': '户外',
                'action': 'suppress',
                'reason': '户外场景功能鞋为刚需'
        }
],
    tags: ['旅行', '舒适', '出片'],
    examples: ['宽松衬衫 + 直筒牛仔裤 + 复古运动鞋 + 斜挎包 + 墨镜'],
  },

  // ═══════════ 特殊场景 ═══════════
  {
    id: 'occ_021',
    module: 'occasion',
    rule: '婚礼宾客不穿白/不穿黑（中式）',
    desc: '西式婚礼女宾不抢新娘风采，白色连衣裙留给新娘。中式婚礼忌纯黑穿搭。不确定时选粉彩色系/酒红/藏蓝。',
    condition: { field: '场景', op: 'eq', value: '婚礼' },
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋'],
    scenes: ['婚礼'],
    tags: ['婚礼', '礼仪', '避雷'],
    examples: [],
  },

  // ═══════════ 周末Brunch ═══════════
  {
    id: 'occ_022',
    module: 'occasion',
    rule: 'Brunch smart casual 底线',
    desc: 'Brunch 是"精致休闲"——比日常多一点点用心，但不要用力过猛。拒绝全套正装，也拒绝刚起床的睡衣感。',
    condition: { field: '场景', op: 'eq', value: '周末brunch' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋'],
    scenes: BRUNCH_SCENES,
    tags: ['brunch', '精致休闲', 'smart-casual'],
    examples: [
      '亚麻衬衫 + 直筒牛仔裤 + 乐福鞋',
      '针织短袖 + A字半裙 + 平底凉鞋',
    ],
  },
  {
    id: 'occ_023',
    module: 'occasion',
    rule: 'Brunch 避免运动装/睡衣风',
    desc: 'Brunch 社交属性决定不能穿卫衣套装或运动裤。至少一条非运动面料的单品把整体拉回精致线。',
    condition: { field: '场景', op: 'eq', value: '周末brunch' },
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋'],
    scenes: BRUNCH_SCENES,
    tags: ['brunch', '避雷', '运动装'],
    examples: [],
  },
  {
    id: 'occ_024',
    module: 'occasion',
    rule: 'Brunch 一件出片单品',
    desc: 'Brunch 不拍照 ≈ 没去过。准备一件"镜头感"单品：特别的墨镜、好看的帽子、质感包、亮色鞋。',
    condition: { field: '场景', op: 'eq', value: '周末brunch' },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋'],
    scenes: BRUNCH_SCENES,
    tags: ['brunch', '出片', '配饰'],
    examples: ['宽檐帽 + 素色穿搭', '亮色斜挎包 + 全白穿搭'],
  },
  {
    id: 'occ_025',
    module: 'occasion',
    rule: 'Brunch 女生裙装/套装优先',
    desc: '女生 brunch 可选连衣裙或同色系上下装两件套。长度膝盖以上为宜，搭配草编包/腋下包。',
    condition: { field: '场景', op: 'eq', value: '周末brunch' },
    type: 'prefer',
    gender: 'female',
    priority: 7,
    season: ['春', '夏'],
    scenes: BRUNCH_SCENES,
    tags: ['brunch', '女生', '裙装'],
    examples: ['碎花连衣裙 + 草编包 + 平底凉拖', '针织两件套 + 腋下包 + 小白鞋'],
  },
  {
    id: 'occ_026',
    module: 'occasion',
    rule: 'Brunch 男生亚麻/针织质感',
    desc: '男生 brunch 选质感面料（亚麻衬衫/针织Polo/轻薄毛衣）+ 修身休闲裤 + 皮质小白鞋或乐福。比日常多一寸精致。',
    condition: { field: '场景', op: 'eq', value: '周末brunch' },
    type: 'prefer',
    gender: 'male',
    priority: 7,
    season: ['春', '夏', '秋'],
    scenes: BRUNCH_SCENES,
    tags: ['brunch', '男生', '质感'],
    examples: ['亚麻白衬衫 + 卡其修身裤 + 棕色乐福鞋 + 墨镜'],
  },

  // ═══════════ 书店/咖啡馆独处 ═══════════
  {
    id: 'occ_027',
    module: 'occasion',
    rule: '书店咖啡馆舒适优先',
    desc: '长时间坐着看书/办公，下装必须不勒腰不卡裆——松紧腰、阔腿裤、直筒裤是王道。紧身牛仔裤坐两小时就想走。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: SOLO_SCENES,
    tags: ['独处', '舒适', '久坐'],
    examples: ['宽松针织衫 + 阔腿裤 + 平底鞋', 'oversized衬衫 + 直筒牛仔裤'],
  },
  {
    id: 'occ_028',
    module: 'occasion',
    rule: '书店咖啡馆必须叠穿应对空调',
    desc: '咖啡馆/书店空调通常偏冷，必须有一件可穿脱的外层——开衫/衬衫外套/轻薄夹克。热了脱、冷了穿。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['夏'],
    scenes: SOLO_SCENES,
    tags: ['独处', '空调', '叠穿'],
    examples: ['吊带裙 + 轻薄开衫（随身带）', 'T恤 + 衬衫外套'],
  },
  {
    id: 'occ_029',
    module: 'occasion',
    rule: '书店咖啡馆文艺/知识分子风格友好',
    desc: '独处场景是文艺风、学院风、知识分子风的主场。粗框眼镜、帆布袋、大地色系、宽松廓形都合理。大胆穿出"不在意潮流"的感觉。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: SOLO_SCENES,
    tags: ['独处', '文艺', '知识分子', '学院'],
    examples: [
      '宽松白衬衫 + 卡其阔腿裤 + 帆布袋 + 粗框眼镜',
      '深灰毛衣 + 直筒牛仔裤 + 皮质托特包',
    ],
  },
  {
    id: 'occ_030',
    module: 'occasion',
    rule: '书店咖啡馆避免过分正式',
    desc: '西装套装、高跟鞋、手拿包在书店/咖啡馆格格不入。穿得太像来开会而非来看书，破坏独处氛围。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: SOLO_SCENES,
    tags: ['独处', '避雷', '正式'],
    examples: [],
  },
  {
    id: 'occ_031',
    module: 'occasion',
    rule: '书店咖啡馆鞋要舒服',
    desc: '可能在书店站很久翻书，可能步行前往。选平底鞋/帆布鞋/乐福鞋/低跟短靴。禁新鞋磨脚、禁细高跟。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'must',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: SOLO_SCENES,
    tags: ['独处', '鞋', '舒适'],
    examples: ['帆布鞋 + 宽松牛仔裤', '乐福鞋 + 阔腿裤'],
  },
  {
    id: 'occ_032',
    module: 'occasion',
    rule: '书店咖啡馆避免过于暴露',
    desc: '安静独处场合，深V/露背/超短裙显突兀且不自在。领口和裙长适度保守，舒适感更强。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'avoid',
    gender: 'female',
    priority: 8,
    season: ['春', '夏'],
    scenes: SOLO_SCENES,
    tags: ['独处', '避雷', '暴露'],
    examples: [],
  },
  {
    id: 'occ_033',
    module: 'occasion',
    rule: '书店咖啡馆低饱和色系',
    desc: '书店/咖啡馆氛围沉静，穿搭色调跟随环境——燕麦色、灰蓝、卡其、米白、灰粉等低饱和色最和谐。荧光色、大Logo破坏宁静感。',
    condition: { field: '场景', op: 'eq', value: '书店咖啡馆独处' },
    type: 'prefer',
    gender: 'unisex',
    priority: 7,
    season: ['春', '夏', '秋', '冬'],
    scenes: SOLO_SCENES,
    tags: ['独处', '色彩', '低饱和', '氛围'],
    examples: ['燕麦色毛衣 + 灰蓝直筒裤', '米白亚麻衫 + 卡其阔腿裤'],
  },

  // ═══════════ 前男友也在的聚会 ═══════════
  {
    id: 'occ_034',
    module: 'occasion',
    rule: '穿被夸过的战袍，不穿新衣',
    desc: '前男友聚会的黄金法则：穿你穿过且被夸过的单品，不冒险穿新衣服。熟悉感带来松弛，松弛感是最高级的赢。新衣的忐忑写在脸上比穿错更致命。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '战袍', '自信', '松弛感'],
    examples: ['那条你穿去生日被三个朋友夸过的连衣裙'],
  },
  {
    id: 'occ_035',
    module: 'occasion',
    rule: 'effortless > 用力过猛',
    desc: '看似不费力、实则每件都讲究。全身新衣+全妆+新发型=太用力=还在意。effortless chic才是"我本来就过得很好"。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'must',
    gender: 'unisex',
    priority: 10,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '松弛感', 'effortless'],
    examples: ['常穿的白衬衫 + 最合身的那条牛仔裤 + 日常戴的手表'],
  },
  {
    id: 'occ_036',
    module: 'occasion',
    rule: '避免过度性感',
    desc: '深V/超短/露背/透视——在ex面前=在示威，反而暴露还在意。得体的性感（合身不贴身、微露不暴露）才是姿态好看。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'avoid',
    gender: 'female',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '避雷', '性感', '用力过猛'],
    examples: [],
  },
  {
    id: 'occ_037',
    module: 'occasion',
    rule: '避免邋遢/太素',
    desc: '另一个极端：素颜+运动服+拖鞋=像被打败了。至少要看起来"有在好好生活"——干净的皮肤、梳理过的头发、起码一条非运动单品。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'avoid',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '避雷', '邋遢', '状态'],
    examples: [],
  },
  {
    id: 'occ_038',
    module: 'occasion',
    rule: '一件低调亮点',
    desc: '一件够——特别的项链、好表、质感鞋。不是全身上下都在"看我看我"，而是有人注意到的时候刚好可以轻描淡写。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'prefer',
    gender: 'unisex',
    priority: 8,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '亮点', '低调', '配饰'],
    examples: ['素色穿搭 + 一条有故事感的项链', '基础款一身 + 一只质感好的表'],
  },
  {
    id: 'occ_039',
    module: 'occasion',
    rule: '穿你最擅长驾驭的风格',
    desc: '不是尝试新风格的时候。平时简约就别突然法式碎花，平时街头就别硬穿西装。稳定的风格=稳定的自我认同。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'must',
    gender: 'unisex',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '风格', '自我认同'],
    examples: [],
  },
  {
    id: 'occ_040',
    module: 'occasion',
    rule: '男生整洁>潮',
    desc: '男生的ex聚会：干净指甲、清新口气、熨过的衣领、擦过的鞋，比任何潮牌logo都管用。"他看起来过得很整齐"比"他穿得很贵"杀伤力大。',
    condition: { field: '场景', op: 'eq', value: '前男友聚会' },
    type: 'must',
    gender: 'male',
    priority: 9,
    season: ['春', '夏', '秋', '冬'],
    scenes: EX_SCENES,
    tags: ['前男友', '男生', '整洁', '状态'],
    examples: ['熨过的牛津纺衬衫 + 干净的修身牛仔裤 + 擦过的皮鞋'],
  },
];
